apiVersion: statgate.io/v1alpha1
kind: CanaryRollout
metadata:
  name: demo-rollout
  namespace: statgate-demo
spec:
  targetRef: demo-canary
  stableServiceRef: demo-stable
  canaryServiceRef: demo-canary
  virtualServiceRef: demo-vs
  prometheusURL: "http://prometheus-server.monitoring.svc.cluster.local:9090"
  analysis:
    alpha: 0.05
    beta: 0.05
    analysisIntervalSeconds: 10
    metrics:
      - name: error-rate
        canaryTotalQuery: 'sum(http_requests_total{version="canary"})'
        canaryFailureQuery: 'sum(http_requests_total{status_code=~"5..",version="canary"}) or vector(0)'
        stableTotalQuery: 'sum(http_requests_total{version="stable"})'
        stableFailureQuery: 'sum(http_requests_total{status_code=~"5..",version="stable"}) or vector(0)'
        delta: 0.05
  steps:
    - weight: 5
      pauseSeconds: 60
    - weight: 25
      pauseSeconds: 60
    - weight: 50
      pauseSeconds: 60
    - weight: 100
      pauseSeconds: 0
  paused: false
  abort: false
