apiVersion: v1
kind: Service
metadata:
  name: statgate-controller-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: statgate
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: metrics
spec:
  selector:
    app: statgate-controller
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
  type: ClusterIP
